-- Foregin key to define table relations
-- CAR_ID becomes foreign key

CREATE TABLE CAR (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    MAKE VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    PRICE NUMERIC(19, 2) NOT NULL
);

CREATE TABLE PERSON (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    GENDER VARCHAR(7) NOT NULL,
    EMAIL VARCHAR(150),
    DATE_OF_BIRTH DATE NOT NULL,
    COUNTRY_OF_BIRTH VARCHAR(50) NOT NULL,
    CAR_ID BIGINT REFERENCES CAR (ID),
    UNIQUE(CAR_ID)
);

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, GENDER, EMAIL, DATE_OF_BIRTH, COUNTRY_OF_BIRTH)
VALUES ('DUSTIN', 'BAEK', 'MALE', 'kbbaek18@gmail.com', DATE '1998-09-04', 'SOUTH KOREA');

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, GENDER, EMAIL, DATE_OF_BIRTH, COUNTRY_OF_BIRTH)
VALUES ('CHRISTINE', 'KWON', 'FEMALE', 'christine@gmail.com', DATE '1998-04-09', 'UK');

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, GENDER, EMAIL, DATE_OF_BIRTH, COUNTRY_OF_BIRTH)
VALUES ('WOONGJAE', 'BAEK', 'MALE', NULL, DATE '1996-05-31', 'JAPAN');

INSERT INTO CAR (MAKE, MODEL, PRICE)
VALUES ('LAND ROVER', 'STERLING', '87665.38');

INSERT INTO CAR (MAKE, MODEL, PRICE)
VALUES ('GMC', 'ACADIA', '17662.69');
