-- Foregin key to define table relations
-- CAR_ID becomes foreign key

CREATE TABLE CAR (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    MAKE VARCHAR(100) NOT NULL,
    MODEL VARCHAR(100) NOT NULL,
    PRICE NUMERIC(19, 2) NOT NULL
);

CREATE TABLE PERSON (
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    GENDER VARCHAR(7) NOT NULL,
    EMAIL VARCHAR(150),
    DATE_OF_BIRTH DATE NOT NULL,
    COUNTRY_OF_BIRTH VARCHAR(50) NOT NULL,
    CAR_ID BIGINT REFERENCES CAR (ID),
    UNIQUE(CAR_ID)
);

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, GENDER, EMAIL, DATE_OF_BIRTH, COUNTRY_OF_BIRTH)
VALUES ('FOO', 'BAR', 'MALE', 'FOOBAR@gmail.com', DATE 'XXXX-XX-XX', 'US');

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, GENDER, EMAIL, DATE_OF_BIRTH, COUNTRY_OF_BIRTH)
VALUES ('BAR', 'FOO', 'FEMALE', 'BARFOO@gmail.com', DATE 'XXXX-XX-XX', 'US');

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, GENDER, EMAIL, DATE_OF_BIRTH, COUNTRY_OF_BIRTH)
VALUES ('ASDF', 'ASDF', 'MALE', NULL, DATE 'XXXX-XX-XX', 'US');

INSERT INTO CAR (MAKE, MODEL, PRICE)
VALUES ('LAND ROVER', 'STERLING', '87665.38');

INSERT INTO CAR (MAKE, MODEL, PRICE)
VALUES ('GMC', 'ACADIA', '17662.69');
